# Generated by Django 5.1.6 on 2025-02-07 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='status',
        ),
    ]
