# Generated by Django 5.1.6 on 2025-02-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_is_verified_email_emailverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
